
services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todopass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  tomcat:
    build:
      context: ./backend
      dockerfile: Dockerfile.tomcat
    container_name: todo_tomcat
    depends_on:
      mysql:
        condition: service_healthy
    environment:
        - DB_HOST=mysql
        - DB_PORT=3306
        - DB_NAME=todo_db
        - DB_USER=todouser
        - DB_PASSWORD=todopass
        # - JAVA_TOOL_OPTIONS=-javaagent:/opt/opentelemetry-javaagent.jar
        # - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
        # - OTEL_SERVICE_NAME=tomcat-service
    ports:
      - "8080:8080"
    restart: always


  # otel-collector:
  #   image: otel/opentelemetry-collector-contrib:latest
  #   container_name: otel-collector
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
  #   ports:
  #     - "1888:1888" # pprof extension
  #     - "8888:8888" # Prometheus metrics exposed by the Collector
  #     - "8889:8889" # Prometheus exporter metrics
  #     - "13133:13133" # health_check extension
  #     - "4317:4317" # OTLP gRPC receiver
  #     - "4318:4318" # OTLP http receiver
  #     - "55679:55679" # zpages extension


  # jaeger:
  #   container_name: jaeger
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - "6831:6831/udp"
  #     - "6832:6832/udp"
  #     - "5778:5778"
  #     - "16686:16686"
  #     - "14250:14250"
  #     - "14268:14268"
  #     - "14269:14269"
  #     - "9411:9411"

volumes:
  db_data: